wangzhigang:
  name: "wangzhigang"
  age: 30
  sex: "\u7537"

wanghuihan:
  girl:
    name: "wanghuihan"
    age: 7
    sex: "\u5973"

spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml