wanghuihan:
  girl:
    name: "wanghuihan100"
    age: 7
    sex: "女"

wangzhigang:
  name: "wangzhigang00000"
  age: 30
  sex: "男"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_test_db?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 800125
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource